import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F2F7F3",
  surface: "#FFFFFF",
  surfaceSoft: "#F7FBF7",
  text: "#10251B",
  textMuted: "#647067",
  green: "#14532D",
  greenDeep: "#355A2C",
  greenSoft: "#E7F4EA",
  greenTint: "#DCECDC",
  yellowSoft: "#F7E9B8",
  border: "#DDE7DE",
  placeholder: "#94A3B8",
  link: "#0EA5E9",
};

export const METRICS = {
  phoneMaxWidth: 430,
  padH: 18,
  padTop: 34,
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Platform.OS === "web" ? "#EAF0EA" : COLORS.bg,
  },
  phone: {
    flex: 1,
    width: "100%",
    maxWidth: METRICS.phoneMaxWidth,
    backgroundColor: COLORS.bg,
    paddingHorizontal: 0,
    paddingTop: 28,
    paddingBottom: Platform.OS === "android" ? 18 : 0,
  },
  loading: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.bg,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  backBtn: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: COLORS.surface,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: COLORS.border,
    marginRight: 12,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: COLORS.text,
    textAlign: "left",
  },
  headerSub: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
    color: COLORS.textMuted,
    fontWeight: "600",
  },
  heroCard: {
    flexDirection: "row",
    alignItems: "center",
    padding: 16,
    borderRadius: 24,
    backgroundColor: COLORS.greenDeep,
    marginBottom: 14,
    shadowColor: "#16311E",
    shadowOpacity: 0.14,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  heroIconWrap: {
    width: 48,
    height: 48,
    borderRadius: 18,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  heroCopy: {
    flex: 1,
    minWidth: 0,
  },
  heroTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "900",
  },
  heroText: {
    marginTop: 4,
    color: "rgba(255,255,255,0.8)",
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  heroCount: {
    minWidth: 66,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    marginLeft: 10,
  },
  heroCountValue: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "900",
  },
  heroCountLabel: {
    marginTop: 2,
    color: "rgba(255,255,255,0.76)",
    fontSize: 10,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  searchWrap: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 18,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: COLORS.surface,
    marginHorizontal: 16,
    marginBottom: 12,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    paddingLeft: 9,
    color: COLORS.text,
    fontSize: 14,
  },
  suggestionsContainer: {
    backgroundColor: COLORS.surface,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    overflow: "hidden",
  },
  suggestionItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.border,
    flexDirection: "row",
    alignItems: "center",
  },
  suggestionText: {
    flex: 1,
    marginLeft: 8,
    color: COLORS.text,
    fontWeight: "700",
  },
  filterBlock: {
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  filterTitle: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "900",
  },
  filterSubtitle: {
    marginTop: 4,
    color: COLORS.textMuted,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: "600",
  },
  filterContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  chip: {
    paddingVertical: 8,
    paddingHorizontal: 14,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
  },
  chipActive: {
    backgroundColor: COLORS.green,
    borderColor: COLORS.green,
  },
  chipText: {
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: "900",
    textTransform: "capitalize",
  },
  chipTextActive: {
    color: "#FFFFFF",
  },
  listContent: {
    paddingBottom: 38,
    gap: 12,
  },
  card: {
    backgroundColor: COLORS.surface,
    padding: 0,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: COLORS.border,
    overflow: "hidden",
  },
  cardTop: {
    flexDirection: "row",
    alignItems: "center",
  },
  cardIcon: {
    width: 42,
    height: 42,
    borderRadius: 15,
    backgroundColor: COLORS.greenSoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  cardCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    fontSize: 18,
    lineHeight: 23,
    fontWeight: "900",
    color: COLORS.text,
  },
  metaRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
  },
  metaPill: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "#EEF4EE",
  },
  metaPillWarning: {
    backgroundColor: COLORS.yellowSoft,
  },
  metaText: {
    fontSize: 10,
    color: "#47604D",
    fontWeight: "900",
  },
  metaTextWarning: {
    color: "#8C5A11",
  },
  desc: {
    fontSize: 13,
    color: COLORS.textMuted,
    lineHeight: 20,
    fontWeight: "600",
  },
  attachmentHint: {
    marginTop: 10,
    color: "#647835",
    fontSize: 12,
    fontWeight: "900",
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: 52,
  },
  emptyTitle: {
    marginTop: 10,
    color: COLORS.text,
    fontWeight: "900",
  },
  emptyText: {
    marginTop: 4,
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  modalBox: {
    flex: 1,
    width: "100%",
    maxWidth: 430,
    alignSelf: "center",
    backgroundColor: COLORS.bg,
    paddingHorizontal: 16,
    paddingTop: 28,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 28,
  },
  modalIcon: {
    width: 40,
    height: 40,
    borderRadius: 14,
    backgroundColor: COLORS.greenSoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  modalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  modalTitle: {
    color: COLORS.text,
    fontSize: 29,
    lineHeight: 36,
    fontWeight: "900",
  },
  closeIcon: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.surface,
  },
  modalDesc: {
    color: COLORS.text,
    lineHeight: 25,
    fontSize: 16,
    fontWeight: "600",
    marginTop: 16,
  },
  attachments: {
    marginTop: 14,
  },
  attachHeader: {
    marginBottom: 8,
    fontWeight: "900",
    color: COLORS.text,
  },
  attachmentImage: {
    width: "100%",
    height: 180,
    marginTop: 8,
    borderRadius: 14,
    backgroundColor: "#E5E7EB",
  },
  fileRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
  },
  link: {
    color: COLORS.link,
    marginLeft: 8,
    fontWeight: "800",
    flex: 1,
  },
  imageViewerScreen: {
    flex: 1,
    backgroundColor: "#0F172A",
  },
  imageViewerHeader: {
    paddingTop: Platform.OS === "ios" ? 56 : 18,
    paddingHorizontal: 16,
    paddingBottom: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  imageViewerBack: {
    alignSelf: "flex-start",
    minHeight: 42,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.14)",
    flexDirection: "row",
    alignItems: "center",
  },
  imageViewerBackText: {
    marginLeft: 4,
    color: "#FFFFFF",
    fontSize: 15,
    fontWeight: "800",
  },
  imageViewerControls: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  imageViewerControlBtn: {
    minHeight: 40,
    minWidth: 40,
    paddingHorizontal: 12,
    borderRadius: 14,
    backgroundColor: "rgba(255,255,255,0.14)",
    alignItems: "center",
    justifyContent: "center",
  },
  imageViewerControlText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "900",
  },
  imageViewerTitle: {
    color: "rgba(255,255,255,0.88)",
    fontSize: 13,
    lineHeight: 18,
    fontWeight: "700",
    paddingHorizontal: 16,
    paddingBottom: 10,
  },
  imageViewerBody: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  imageViewerScrollContent: {
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 16,
    paddingBottom: 28,
  },
  fullscreenImage: {
    width: "100%",
    height: "100%",
  },
});

export default styles;
