import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F2F7F3",
  surface: "#FFFFFF",
  surfaceSoft: "#F7FBF7",
  text: "#10251B",
  textMuted: "#647067",
  green: "#14532D",
  greenDeep: "#355A2C",
  greenSoft: "#E7F4EA",
  border: "#DFE9E1",
  placeholder: "#94A3B8",
  danger: "#DC2626",
};

export const METRICS = {
  phoneMaxWidth: 430,
  padH: 18,
  padTop: 34,
  inputH: 50,
  btnH: 52,
};

const styles = StyleSheet.create({
  webFrame: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Platform.OS === "web" ? "#EAF0EA" : COLORS.bg,
  },
  phone: {
    flex: 1,
    width: "100%",
    maxWidth: METRICS.phoneMaxWidth,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    paddingHorizontal: METRICS.padH,
    paddingTop: Platform.OS === "android" ? 26 : 20,
    paddingBottom: Platform.OS === "android" ? 42 : 30,
  },
  headerRow: {
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  headerCopy: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  headerRightSpacer: {
    width: 44,
    height: 44,
  },
  headerTitle: {
    textAlign: "center",
    fontSize: 15,
    fontWeight: "900",
    color: COLORS.text,
  },
  subText: {
    marginTop: 2,
    textAlign: "center",
    fontSize: 11,
    color: COLORS.textMuted,
    fontWeight: "700",
  },
  securityHero: {
    alignItems: "center",
    paddingHorizontal: 24,
    paddingTop: 12,
    paddingBottom: 18,
    backgroundColor: "transparent",
    borderWidth: 0,
    marginBottom: 6,
    shadowOpacity: 0,
    elevation: 0,
  },
  heroIcon: {
    width: 86,
    height: 86,
    borderRadius: 28,
    backgroundColor: COLORS.greenSoft,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  heroCopy: {
    alignItems: "center",
  },
  heroTitle: {
    color: COLORS.text,
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
  },
  heroText: {
    marginTop: 8,
    color: COLORS.textMuted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: "600",
    textAlign: "center",
  },
  sectionCard: {
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    padding: 18,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#0F2319",
    shadowOpacity: 0.06,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "900",
    color: COLORS.text,
  },
  inputWrap: {
    marginTop: 14,
  },
  inputLabel: {
    marginBottom: 7,
    color: COLORS.text,
    fontSize: 12,
    fontWeight: "900",
  },
  input: {
    width: "100%",
    minHeight: 46,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 999,
    paddingHorizontal: 16,
    color: COLORS.text,
    backgroundColor: "#FBFDFC",
    fontSize: 15,
  },
  error: {
    color: COLORS.danger,
    marginTop: 8,
    fontSize: 12,
    fontWeight: "700",
  },
  ruleGrid: {
    marginTop: 16,
  },
  ruleHeader: {
    marginBottom: 8,
    color: COLORS.textMuted,
    fontSize: 10,
    fontWeight: "900",
  },
  rulePill: {
    minHeight: 22,
    flexDirection: "row",
    alignItems: "center",
  },
  ruleDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    marginRight: 8,
  },
  rulePillOk: {},
  ruleText: {
    flex: 1,
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "700",
  },
  ruleTextOk: {
    color: COLORS.text,
  },
  button: {
    width: "100%",
    height: METRICS.btnH,
    backgroundColor: COLORS.green,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 22,
    shadowColor: COLORS.green,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  buttonText: {
    color: COLORS.text,
    fontWeight: "900",
    fontSize: 15,
  },
  twoFAWrapper: {
    marginTop: 14,
    backgroundColor: COLORS.surface,
    borderRadius: 8,
    padding: 16,
    borderWidth: 1,
    borderColor: COLORS.border,
    shadowColor: "#0F2319",
    shadowOpacity: 0.05,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 2,
  },
  twoFATop: {
    flexDirection: "row",
    alignItems: "center",
  },
  twoFAIcon: {
    width: 46,
    height: 46,
    borderRadius: 8,
    backgroundColor: COLORS.greenSoft,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  twoFACopy: {
    flex: 1,
    marginRight: 8,
  },
  subInfo: {
    marginTop: 4,
    fontSize: 12,
    color: COLORS.textMuted,
    fontWeight: "600",
    lineHeight: 17,
  },
  status: {
    alignSelf: "flex-start",
    marginTop: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "#F1F5F1",
    color: "#55635B",
    fontSize: 12,
    fontWeight: "900",
    overflow: "hidden",
  },
  statusEnabled: {
    backgroundColor: "#DCF3E0",
    color: "#166534",
  },
});

export default styles;
