import { Platform, StyleSheet } from "react-native";

export const COLORS = {
  bg: "#F6F8F6",
  surface: "#FFFFFF",
  surfaceSoft: "#F7FAF7",
  text: "#10251B",
  textMuted: "#68736B",
  green: "#14532D",
  greenSoft: "#E7F4EA",
  border: "#E5ECE6",
  placeholder: "#94A3B8",
  danger: "#DC2626",
};

export const METRICS = {
  phoneMaxWidth: 430,
  padH: 20,
  inputH: 42,
  btnH: 52,
};

const styles = StyleSheet.create({
  webFrame: {
    flex: 1,
    alignItems: "center",
    backgroundColor: Platform.OS === "web" ? "#EDF2ED" : COLORS.bg,
  },
  phone: {
    flex: 1,
    width: "100%",
    maxWidth: METRICS.phoneMaxWidth,
    backgroundColor: COLORS.bg,
  },
  scrollContent: {
    paddingHorizontal: METRICS.padH,
    paddingTop: Platform.OS === "android" ? 26 : 20,
    paddingBottom: Platform.OS === "android" ? 42 : 30,
  },
  headerRow: {
    height: 44,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  backBtn: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: "center",
    justifyContent: "center",
  },
  headerSpacer: {
    width: 44,
    height: 44,
  },
  headerTitle: {
    flex: 1,
    textAlign: "center",
    fontSize: 15,
    fontWeight: "900",
    color: COLORS.text,
  },
  subText: {
    color: COLORS.textMuted,
    fontSize: 12,
    fontWeight: "600",
  },
  profileHero: {
    alignItems: "center",
    paddingTop: 8,
    paddingBottom: 26,
  },
  avatarRing: {
    width: 112,
    height: 112,
    borderRadius: 56,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 14,
  },
  avatar: {
    width: 104,
    height: 104,
    borderRadius: 52,
    backgroundColor: COLORS.surfaceSoft,
  },
  avatarBadge: {
    position: "absolute",
    right: 5,
    bottom: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    borderWidth: 3,
    alignItems: "center",
    justifyContent: "center",
  },
  profileName: {
    maxWidth: "92%",
    color: COLORS.text,
    fontSize: 20,
    fontWeight: "900",
    textAlign: "center",
  },
  profileEmail: {
    maxWidth: "92%",
    marginTop: 5,
    color: COLORS.textMuted,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  sectionTitle: {
    color: COLORS.text,
    fontSize: 16,
    fontWeight: "900",
    marginTop: 10,
    marginBottom: 20,
  },
  sectionGroup: {
    marginBottom: 20,
  },
  readOnlyField: {
    minHeight: 58,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    paddingHorizontal: 14,
    marginBottom: 20,
    shadowColor: "#10251B",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  formRow: {
    minHeight: 64,
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    paddingHorizontal: 14,
    marginBottom: 20,
    shadowColor: "#10251B",
    shadowOpacity: 0.04,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 1,
  },
  rowIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  formRowBody: {
    flex: 1,
    minWidth: 0,
  },
  rowLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 2,
  },
  rowValue: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "800",
  },
  rowInput: {
    width: "100%",
    minHeight: 32,
    padding: 0,
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "800",
  },
  rowPicker: {
    width: "100%",
    minHeight: 40,
    marginVertical: -8,
    marginLeft: -8,
  },
  readOnlyLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "800",
    marginBottom: 2,
  },
  readOnlyValue: {
    color: COLORS.text,
    fontSize: 14,
    fontWeight: "800",
  },
  addressPreview: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: COLORS.border,
    backgroundColor: COLORS.surface,
    padding: 14,
    marginTop: 2,
  },
  previewLabel: {
    color: COLORS.textMuted,
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    marginBottom: 5,
  },
  previewText: {
    color: COLORS.text,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: "700",
  },
  label: {
    fontSize: 13,
    fontWeight: "900",
    color: COLORS.text,
    marginBottom: 4,
  },
  helper: {
    fontSize: 12,
    color: COLORS.textMuted,
    marginBottom: 8,
    lineHeight: 18,
    fontWeight: "600",
  },
  input: {
    width: "100%",
    minHeight: METRICS.inputH,
    borderWidth: 1,
    borderColor: COLORS.border,
    borderRadius: 10,
    paddingHorizontal: 14,
    color: COLORS.text,
    backgroundColor: COLORS.surface,
    fontSize: 15,
    marginBottom: 14,
  },
  button: {
    width: "100%",
    height: METRICS.btnH,
    backgroundColor: COLORS.green,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 2,
    marginBottom: 12,
    shadowColor: COLORS.green,
    shadowOpacity: 0.16,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  buttonText: {
    color: "#FFFFFF",
    fontWeight: "900",
    fontSize: 15,
  },
  error: {
    color: COLORS.danger,
    marginTop: -6,
    marginBottom: 12,
    fontSize: 12,
    fontWeight: "700",
  },
});

export default styles;